use_frameworks!
platform :ios, '8.0'
inhibit_all_warnings!

target 'EnumCases_Example' do
  pod 'EnumCases', :path => '../'

  target 'EnumCases_Tests' do
    inherit! :search_paths

    pod 'EnumCases', :path => '../'
    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
    pod 'FBSnapshotTestCase'
#    pod 'Nimble-Snapshots'
  end
end
